// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// adtseq
int adtseq(std::string bamFileName, std::string bamOut, std::string adtFasta, int max_dist, std::string sumoutput, std::string adt_panel, int bc_length);
RcppExport SEXP _adtseq_adtseq(SEXP bamFileNameSEXP, SEXP bamOutSEXP, SEXP adtFastaSEXP, SEXP max_distSEXP, SEXP sumoutputSEXP, SEXP adt_panelSEXP, SEXP bc_lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type bamFileName(bamFileNameSEXP);
    Rcpp::traits::input_parameter< std::string >::type bamOut(bamOutSEXP);
    Rcpp::traits::input_parameter< std::string >::type adtFasta(adtFastaSEXP);
    Rcpp::traits::input_parameter< int >::type max_dist(max_distSEXP);
    Rcpp::traits::input_parameter< std::string >::type sumoutput(sumoutputSEXP);
    Rcpp::traits::input_parameter< std::string >::type adt_panel(adt_panelSEXP);
    Rcpp::traits::input_parameter< int >::type bc_length(bc_lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(adtseq(bamFileName, bamOut, adtFasta, max_dist, sumoutput, adt_panel, bc_length));
    return rcpp_result_gen;
END_RCPP
}
// bcExtract
int bcExtract(std::string bamIn, std::string bamOut, std::string sumoutput, std::string cellBC);
RcppExport SEXP _adtseq_bcExtract(SEXP bamInSEXP, SEXP bamOutSEXP, SEXP sumoutputSEXP, SEXP cellBCSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type bamIn(bamInSEXP);
    Rcpp::traits::input_parameter< std::string >::type bamOut(bamOutSEXP);
    Rcpp::traits::input_parameter< std::string >::type sumoutput(sumoutputSEXP);
    Rcpp::traits::input_parameter< std::string >::type cellBC(cellBCSEXP);
    rcpp_result_gen = Rcpp::wrap(bcExtract(bamIn, bamOut, sumoutput, cellBC));
    return rcpp_result_gen;
END_RCPP
}
// icgrEncode
Rcpp::IntegerMatrix icgrEncode(std::string seq);
RcppExport SEXP _adtseq_icgrEncode(SEXP seqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type seq(seqSEXP);
    rcpp_result_gen = Rcpp::wrap(icgrEncode(seq));
    return rcpp_result_gen;
END_RCPP
}
// hdist
Rcpp::IntegerMatrix hdist(std::vector<std::string> umi);
RcppExport SEXP _adtseq_hdist(SEXP umiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type umi(umiSEXP);
    rcpp_result_gen = Rcpp::wrap(hdist(umi));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_adtseq_adtseq", (DL_FUNC) &_adtseq_adtseq, 7},
    {"_adtseq_bcExtract", (DL_FUNC) &_adtseq_bcExtract, 4},
    {"_adtseq_icgrEncode", (DL_FUNC) &_adtseq_icgrEncode, 1},
    {"_adtseq_hdist", (DL_FUNC) &_adtseq_hdist, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_adtseq(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
