# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

adtseq <- function(bamFileName, bamOut, adtFasta, max_dist, sumoutput) {
    .Call('_adtseq_adtseq', PACKAGE = 'adtseq', bamFileName, bamOut, adtFasta, max_dist, sumoutput)
}

bcExtract <- function(bamIn, bamOut, sumoutput, cellBC) {
    .Call('_adtseq_bcExtract', PACKAGE = 'adtseq', bamIn, bamOut, sumoutput, cellBC)
}

